---
rhel_iso: /home/rhel8.3.iso

nodes:
  - name: "ceph1"
    mac: "52:54:00:ab:5a:53"
    disk: "sdb"
  - name: "ceph2"
    mac: "52:54:00:ac:5a:53"
    disk: "sdc"
  - name: "ceph3"
    mac: "52:54:00:ad:5a:53"
    disk: "sdd"